## Gradient Tape

In [1]:
import numpy as np
import tensorflow as tf

#### The gradient tape in TensorFlow

In [5]:
x = tf.Variable(0.)

with tf.GradientTape() as tape:
    y = 2 * x + 3

tape.gradient(y, x)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [9]:
x = tf.Variable(tf.random.uniform((2, 2)))

print('x: ', x)

with tf.GradientTape() as tape:
    y = 2 * x + 3
    
tape.gradient(y, x)

x:  <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.494815  , 0.6266117 ],
       [0.02537656, 0.76595426]], dtype=float32)>


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [7]:
W = tf.Variable(tf.random.uniform((2, 2)))
b = tf.Variable(tf.zeros((2,)))
x = tf.random.uniform((2, 2))

with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b

tape.gradient(y, [W, b])

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1.5390625 , 1.5390625 ],
        [0.74438477, 0.74438477]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>]