## Basics

In [5]:
import numpy as np
from tensorflow.keras.utils import timeseries_dataset_from_array

In [23]:
sequence = np.array([1, 2, 3, 4, 5, 6])
sequence

array([1, 2, 3, 4, 5, 6])

In [26]:
target = np.array([11, 22, 33, 44])

In [50]:
dataset = timeseries_dataset_from_array(
    data=sequence,
    targets=target,
    sampling_rate=1,
    sequence_length=3,
    shuffle=True,
    batch_size=2
)

In [51]:
for inputs, targets in dataset:
    for i in range(inputs.shape[0]):
        print(inputs[i].numpy(), int(targets[i]))

[4 5 6] 44
[2 3 4] 22
[3 4 5] 33
[1 2 3] 11
