## A first look at a neural network

In [1]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

**Loading the MNIST dataset in Keras**

In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [15]:
train_images.shape

(60000, 784)

In [4]:
len(train_labels)

60000

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

**The network architecture**

In [9]:
model = Sequential([
    Dense(512, activation="relu"),
    Dense(10, activation="softmax")
])

**The compilation step**

### Optimizer: Mechanism through which the model will update itself
### Loss function: How the model will be able to measure its performance on the training data
### Metrics: Monitor during training and testing

In [11]:
model.compile(optimizer="rmsprop", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

**Preparing the image data**

In [12]:
train_images = train_images.reshape((60000, 28 * 28))
test_images = test_images.reshape((10000, 28 * 28))

**Rescaling**

In [13]:
train_images = train_images.astype("float32") / 255
test_images = test_images.astype("float32") / 255

**Model Fitting**

In [16]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 4s 2ms/step - loss: 0.2566 - accuracy: 0.9263
Epoch 2/5
469/469 [==============================] - 1s 2ms/step - loss: 0.1038 - accuracy: 0.9689
Epoch 3/5
469/469 [==============================] - 1s 2ms/step - loss: 0.0686 - accuracy: 0.9794
Epoch 4/5
469/469 [==============================] - 1s 2ms/step - loss: 0.0510 - accuracy: 0.9848
Epoch 5/5
469/469 [==============================] - 1s 2ms/step - loss: 0.0377 - accuracy: 0.9884


**Using the model to make predictions**

In [20]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0] # Each index value in that array corresponds to the probability of a digit image

1/1 [==============================] - 0s 15ms/step


array([5.7797273e-10, 6.9134238e-12, 4.8042165e-07, 3.2098301e-06,
       9.0663284e-13, 1.2517556e-09, 7.0684023e-15, 9.9999559e-01,
       2.8546069e-08, 7.0391212e-07], dtype=float32)

In [22]:
predictions[0].argmax() # Highest probability refers to the predicted number

7

In [23]:
predictions[0][7]

0.9999956

In [24]:
test_labels[0]

7

**Evaluating the model on new data**

In [25]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 [==============================] - 1s 2ms/step - loss: 0.0671 - accuracy: 0.9811
test_acc: 0.9811000227928162
