## The gears of neural networks: tensor operations

In [34]:
import time
import numpy as np

### Element-wise operations

In [35]:
def vanilla_add(x, y):
    
    t = x.copy()
    row = x.shape[0]
    column = x.shape[1]
    
    for i in range(row):
        for j in range(column):
            t[i, j] = x[i, j] + y[i, j]
    
    return x

In [36]:
def vanilla_relu(x):
    
    t = x.copy()
    row = x.shape[0]
    column = x.shape[1]
    
    for i in range(row):
        for j in range(column):
            t[i, j] = max(x[i, j], 0)
    
    return x

In [37]:
x = np.random.random((20, 100))
y = np.random.random((20, 100))
t0 = time.time()

### Vanilla Operation

In [38]:
for _ in range(1000):
    
    z = vanilla_add(x, y)
    z = vanilla_relu(z)
    print("Took: {0:.2f} s".format(time.time() - t0))

Took: 3.25 s
Took: 3.25 s
Took: 3.25 s
Took: 3.25 s
Took: 3.26 s
Took: 3.26 s
Took: 3.26 s
Took: 3.26 s
Took: 3.26 s
Took: 3.27 s
Took: 3.27 s
Took: 3.27 s
Took: 3.27 s
Took: 3.27 s
Took: 3.27 s
Took: 3.27 s
Took: 3.27 s
Took: 3.28 s
Took: 3.28 s
Took: 3.28 s
Took: 3.28 s
Took: 3.28 s
Took: 3.28 s
Took: 3.28 s
Took: 3.28 s
Took: 3.29 s
Took: 3.29 s
Took: 3.29 s
Took: 3.29 s
Took: 3.29 s
Took: 3.30 s
Took: 3.30 s
Took: 3.30 s
Took: 3.30 s
Took: 3.30 s
Took: 3.30 s
Took: 3.31 s
Took: 3.31 s
Took: 3.31 s
Took: 3.31 s
Took: 3.31 s
Took: 3.32 s
Took: 3.32 s
Took: 3.32 s
Took: 3.32 s
Took: 3.32 s
Took: 3.32 s
Took: 3.32 s
Took: 3.32 s
Took: 3.33 s
Took: 3.33 s
Took: 3.33 s
Took: 3.33 s
Took: 3.33 s
Took: 3.33 s
Took: 3.33 s
Took: 3.33 s
Took: 3.33 s
Took: 3.34 s
Took: 3.34 s
Took: 3.34 s
Took: 3.34 s
Took: 3.34 s
Took: 3.34 s
Took: 3.34 s
Took: 3.34 s
Took: 3.35 s
Took: 3.35 s
Took: 3.35 s
Took: 3.35 s
Took: 3.35 s
Took: 3.35 s
Took: 3.35 s
Took: 3.35 s
Took: 3.36 s
Took: 3.36 s
Took: 3.36 s

Took: 4.28 s
Took: 4.28 s
Took: 4.29 s
Took: 4.29 s
Took: 4.29 s
Took: 4.29 s
Took: 4.29 s
Took: 4.30 s
Took: 4.30 s
Took: 4.30 s
Took: 4.30 s
Took: 4.30 s
Took: 4.30 s
Took: 4.30 s
Took: 4.30 s
Took: 4.31 s
Took: 4.31 s
Took: 4.31 s
Took: 4.31 s
Took: 4.31 s
Took: 4.31 s
Took: 4.31 s
Took: 4.31 s
Took: 4.31 s
Took: 4.32 s
Took: 4.32 s
Took: 4.32 s
Took: 4.32 s
Took: 4.32 s
Took: 4.32 s
Took: 4.33 s
Took: 4.33 s
Took: 4.33 s
Took: 4.33 s
Took: 4.33 s
Took: 4.33 s
Took: 4.33 s
Took: 4.34 s
Took: 4.34 s
Took: 4.34 s
Took: 4.34 s
Took: 4.34 s
Took: 4.34 s
Took: 4.35 s
Took: 4.35 s
Took: 4.35 s
Took: 4.35 s
Took: 4.35 s
Took: 4.36 s
Took: 4.36 s
Took: 4.36 s
Took: 4.36 s
Took: 4.36 s
Took: 4.36 s
Took: 4.37 s
Took: 4.37 s
Took: 4.37 s
Took: 4.37 s
Took: 4.37 s
Took: 4.37 s
Took: 4.37 s
Took: 4.37 s
Took: 4.38 s
Took: 4.38 s
Took: 4.38 s
Took: 4.38 s
Took: 4.38 s
Took: 4.38 s
Took: 4.38 s
Took: 4.38 s
Took: 4.39 s
Took: 4.39 s
Took: 4.39 s
Took: 4.39 s
Took: 4.39 s
Took: 4.39 s
Took: 4.40 s

### Built-in Operation

In [39]:
t0 = time.time()

for _ in range(1000):
    
    z = x + y
    z = np.maximum(z, 0.)

    print("Took: {0:.2f} s".format(time.time() - t0))

Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.00 s
Took: 0.01 s
Took: 0.01 s
Took: 0.01 s
Took: 0.01 s
Took: 0.01 s
Took: 0.01 s
Took: 0.01 s

### Broadcasting

#### Shapes of two tensors are when diffent

In [58]:
x = np.random.random((5, 10))
y = np.random.random((10,))

In [59]:
y = np.expand_dims(y, axis=0)
y.shape

(1, 10)

In [60]:
y = np.concatenate([y] * 5, axis=0)
y.shape

(5, 10)

#### Vanilla Broadcasting

In [52]:
def vanilla_add_matrix_and_vector(x, y):

    x = x.copy()
    row = x.shape[0]
    column = x.shape[1]

    for i in range(row):
        for j in range(column):
            x[i, j] += y[j]
    
    return x

In [61]:
x = np.random.random((5, 10))
y = np.random.random((10,))
z = vanilla_add_matrix_and_vector(x, y)
z.shape

(5, 10)

#### Built-in Broadcasting

In [62]:
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)

### Tensor product

In [63]:
x = np.random.random((32,))
y = np.random.random((32,))
z = np.dot(x, y)

In [71]:
def vanilla_vector_dot(x, y):
    
    z = 0.
    
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    
    return z

In [72]:
vanilla_vector_dot(x,y)

7.83736919484267

In [74]:
def vanilla_matrix_vector_dot(x, y):
    
    z = np.zeros(x.shape[0])
    
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    
    return z

In [79]:
x = np.array([[1,2],[3,4]])
y = np.array([1,2])
vanilla_matrix_vector_dot(x,y)

array([ 5., 11.])

In [81]:
def matrix_vector_dot(x, y):
    
    z = np.zeros(x.shape[0])
    
    for i in range(x.shape[0]):
        z[i] = naive_vector_dot(x[i, :], y)
    
    return z

In [82]:
x = np.array([[1,2],[3,4]])
y = np.array([1,2])
matrix_vector_dot(x,y)

array([ 5., 11.])

In [96]:
def vanilla_matrix_dot(x, y):
    
    z = np.zeros((x.shape[0], y.shape[1]))
    
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row = x[i, :]
            column = y[:, j]
            z[i, j] = vanilla_vector_dot(row, column)
    
    return z

In [99]:
x = np.array([[1,2],[3,4]])
y = np.array([[1], [2]])
vanilla_matrix_dot(x,y)

array([[ 5.],
       [11.]])

### Tensor reshaping

In [87]:
x = np.array([[0., 1.],
             [2., 3.],
             [4., 5.]])
x.shape

(3, 2)

In [88]:
x = x.reshape((6, 1))
x.shape

(6, 1)

In [89]:
x = np.zeros((300, 20))
x = np.transpose(x) # row becomes column and column becomes row
x.shape

(20, 300)

### Geometric Interpretation of Tensor

#### Translation: Moving point in a vector space

In [90]:
p = np.array([1,2])
q = np.array([3,3])
translation = p + q
translation

array([4, 5])

#### Rotation: Conunterclock-wise rotation in a 2D plane by an angle theta

In [95]:
x = np.array([[1, 0],[0 -1]], dtype=object)
y = np.array([[3], [4]], dtype=object)
z = x * y
z

array([[list([1, 0, 1, 0, 1, 0]), list([-1, -1, -1])],
       [list([1, 0, 1, 0, 1, 0, 1, 0]), list([-1, -1, -1, -1])]],
      dtype=object)