# Introduction to Keras and TensorFlow

**All-ones or all-zeros tensors**

In [7]:
import tensorflow as tf
import numpy as np

In [2]:
x = tf.ones(shape=(2, 1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [3]:
x = tf.zeros(shape=(2, 1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


**Random tensors**

In [4]:
x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.) # Bell curve
print(x)

tf.Tensor(
[[ 0.27681914]
 [-0.4419499 ]
 [-0.0832922 ]], shape=(3, 1), dtype=float32)


In [5]:
x = tf.random.uniform(shape=(3, 1), minval=0., maxval=1.) # Square curve
print(x)

tf.Tensor(
[[0.26826024]
 [0.13403046]
 [0.76189375]], shape=(3, 1), dtype=float32)


**NumPy arrays are assignable, Tensor are not**

In [8]:
x = np.ones(shape=(2, 2))
x[0, 0] = 0.

**Creating a TensorFlow variable**

In [10]:
a = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(a)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.6690991 ],
       [ 0.1509742 ],
       [-0.73459554]], dtype=float32)>


**Assigning a value to a TensorFlow variable**

In [11]:
a.assign(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

**Assigning a value to a specific location of a TensorFlow variable**

In [13]:
a[0, 0].assign(3.)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

**Using `assign_add`**

In [14]:
a.assign_add(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

#### Tensor operations: Doing math in TensorFlow

In [15]:
a = tf.ones((2, 2))
b = tf.square(a)
c = tf.sqrt(a)
d = b + c
e = tf.matmul(a, b)
e *= d