# Gradient Tape

In [1]:
import tensorflow as tf

**Using the `GradientTape`**

In [3]:
v = tf.Variable(initial_value=3.)

with tf.GradientTape() as tape:
    result = tf.square(v)

gradient = tape.gradient(result, v)
gradient

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

**Using `GradientTape` with constant tensor inputs**

In [7]:
c = tf.constant(3.)

with tf.GradientTape() as tape:
    tape.watch(c)
    result = tf.square(c)

gradient = tape.gradient(result, c)
gradient

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

**Using nested gradient tapes to compute second-order gradients**

In [8]:
time = tf.Variable(0.)

with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position =  4.9 * time ** 2
    speed = inner_tape.gradient(position, time)

acceleration = outer_tape.gradient(speed, time)
acceleration

<tf.Tensor: shape=(), dtype=float32, numpy=9.8>